package configs

public class PageLocatorName {

	public static final String CARAPPROVAL_PAGE = 				"CARApprovalPage"
	public static final String CARTEMPLATES_PAGE = 				"CARTemplatesPage"
	public static final String COMMONLOCATORS_PAGE = 			"CommonLocators"
	public static final String CONTRACTDOCUMENTLIBRARY_PAGE = 	"ContractDocumentLibraryPage"
	public static final String COSTCENTER_PAGE = 				"CostCenterPage"
	public static final String CREATECAR_PAGE = 				"CreateCARPage"
	public static final String DASHBOARDMENU = 					"DashboardMenu"
	public static final String EXECUTECONTRACT_PAGE = 			"ExecuteContractPage"
	public static final String FEATURES_PAGE = 					"FeaturesPage"
	public static final String HEADER_PAGE = 					"HeaderPage"
	public static final String LOCATION_PAGE = 					"LocationPage"
	public static final String LOGIN_PAGE = 					"LoginPage"
	public static final String MAILTEMPLATES_PAGE = 			"MailTemplatesPage"
	public static final String MANAGEALERTSNOTIFICATIONS_PAGE = "ManageAlertsNotificationsPage"
	public static final String MENU_PAGE = 						"MenuPage"
	public static final String ORGANIZATION_PAGE = 				"OrganizationPage"
	public static final String PASSWORDPOLICY_PAGE = 			"PasswordPolicyPage"
	public static final String PAYELEMENTS_PAGE = 				"PayElementsPage"
	public static final String POSITION_PAGE = 					"PositionPage"
	public static final String PROVIDERS_PAGE = 				"ProvidersPage"
	public static final String REGION_PAGE = 					"RegionPage"
	public static final String ROLES_PAGE = 					"RolesPage"
	public static final String SEARCHCONTRACTS_PAGE =			"SearchContractsPage"
	public static final String SPECIALTY_PAGE = 				"SpecialtyPage"
	public static final String TEMPLATELIBRARY_PAGE = 			"TemplateLibraryPage"
	public static final String TERMSCONDITIONS_PAGE = 			"TermsConditionsPage"
	public static final String USERS_PAGE = 					"UsersPage"
	public static final String VIEWCAR_PAGE = 					"ViewCARPage"
	public static final String YOPMAIL_PAGE = 					"YopmailPage"
	public static final String DOCUSIGN_PAGE = 					"DocuSignPage"
	public static final String DASHBOARD_PAGE = 				"DashboardPage"
	public static final String CARSTATUSREPORT_PAGE = 			"CARStatusReportPage"
	public static final String CONTRACTSTATUS_PAGE = 			"ContractStatusPage"
	public static final String ACTIVITYLOG_PAGE = 			    "ActivityLogPage"
	public static final String UPCOMINGRENEWALS_PAGE = 			"UpcomingRenewalsPage"
	public static final String CARDATAREPORT_PAGE = 			"CARDataReportPage"
	public static final String MAILTEMPTOP_PAGE = 				"MailTempTopPage"
	public static final String GMAIL_PAGE = 					"GmailPage"
}
